// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-C7jBRSZdYLxkYcYAibRTodA0yNTTvz8',
    appId: '1:341008381689:android:5e3ef088081e8cfb2fd428',
    messagingSenderId: '341008381689',
    projectId: 'dandaily-todo',
    storageBucket: 'dandaily-todo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiXaeIJriRqxMVKhHs_brJS9qzB9PkJeY',
    appId: '1:341008381689:ios:bec3c39df73b66262fd428',
    messagingSenderId: '341008381689',
    projectId: 'dandaily-todo',
    storageBucket: 'dandaily-todo.firebasestorage.app',
    iosBundleId: 'com.nylo.ios',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCT2jE2qCAtKf268MB6NUkZuChRenpL-GQ',
    appId: '1:341008381689:web:3faf1026381fe0a62fd428',
    messagingSenderId: '341008381689',
    projectId: 'dandaily-todo',
    authDomain: 'dandaily-todo.firebaseapp.com',
    storageBucket: 'dandaily-todo.firebasestorage.app',
    measurementId: 'G-HG16YFB9FT',
  );
}
